name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set working directory
      run: cd $GITHUB_WORKSPACE/ratingapp && ls
  
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
  
    - name: Install dependencies
      run: npm install
  
    - name: Install react-router-dom
      run: npm install react-router-dom
  
    - name: Install js-cookie
      run: npm install js-cookie
  
    - name: Install reactstrap
      run: npm install reactstrap
  
    - name: Run tests
      run: npm test run
